server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Mall_Shaw?useUnicode=true&characterEncoding=utf-8&serverTimezone=EST&createDatabaseIfNotExist=true
    username: root
    password: llld1106
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
