server:
  port: 8081
  servlet:
    path: /rest/service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Mall_Shaw?useUnicode=true&characterEncoding=utf-8&serverTimezone=EST&createDatabaseIfNotExist=true
    username: root
    password: llld1106
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size:
        2500MB
      max-request-size:
        2500MB

redis:
  key:
    prefix:
      authCode: "portal:authCode"
    expire:
      authCode: 120

jwt:
  tokenHeader: Authorization
  secret: "Shaw_Liao"
  expire: 604800
  tokenHead: Bearer

data:
  elasticsearch:
    repositories:
      enable: true
    cluster-node: localhost:9300
    cluster-name: elasticsearch

aws:
  access_key_id: AKIAJMDGWR53JSCU5WMQ
  secret_access_key: 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
  s3:
    bucket: mall-shaw-upload-product
    region: us-east-2
    filename: /logo/brand1/